print('Want to hear 3 jokes?')
input()
print()
print('What happened when the cheese shop exploded?')
input()
print('Da brie was everywhere!')
print()
print('Ready for the second one?')
input()
print()
print('Why did the melons choose not to get married?')
input()
print('Because they cantaloupe!')
print()
print('One more laugh?')
input()
print()
print('How does Darth Vader like his toast?')
input()
print()
print('On the dark side!')
print('I hope you had a good laugh!')
input()
print()